### PR TITLE
Cleaned Gun.cpp code section

### PR DESCRIPTION
**Pull request by Markyroson**
I would suggest this change as it cleans up the bracket appearance somewhat. I have not tested the change however upon first inspection, it appears as if it would not change any of the behaviour.

Do with this as you so wish, just my suggestion.

### CODE REVIEW

**Comment by sampattuzzi** [comment]
Nice work but we can't accept PRs as they wouldn't end up in the course.

**Comment by Markyroson** [comment]
:( Too bad.

**Comment by sampattuzzi** [comment]
We do this because we don't want thing to change between videos, only on screen. But definitely a good exercise to do this. Not waste work.

**Comment by Markyroson** [comment]
Fair enough, that makes sense. Maybe add something to the readme though stating that you will not accept pull requests, in order to save others time and not have their work/time be wasted trying to help?

Good job with the course and good luck! :-D

**Comment by sampattuzzi** [comment]
Good point! Sorry to have wasted you time.

**Pull request closed without merging**
